name: Scheduled Database Dump
on:
  schedule:
    - cron: '0 2 * * *'      # every day at 2 AM UTC
  workflow_dispatch:
jobs:
  run_dump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Setup .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Add SSH keys
      run: |
        mkdir -p ssh_keys
        echo "${{ secrets.EXG_LINUX_KEY_PAIR }}" > ssh_keys/EXG_LINUX_KEY_PAIR.pem
        chmod 600 ssh_keys/EXG_LINUX_KEY_PAIR.pem
        echo "${{ secrets.KAVYA_DJANGO_KEY }}" > ssh_keys/Kavya_django_key.pem
        chmod 600 ssh_keys/Kavya_django_key.pem
    - name: Restore token.json
      run: echo '${{ secrets.TOKEN_JSON }}' > token.json
      
    - name: Run Dump Script with Debug
      run: |
        set -x
        python scheduled_dumps.py

