name: Scheduled Database Dump

on:
  schedule:
    - cron: '0 2 * * *' # every day at 2 AM UTC
  workflow_dispatch:

jobs:
  run_dump:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run dump script
      run: python scheduled_dumps.py
